#! /bin/bash

t=238.1.1.95

if [[ -z $(ip r get $t | grep 'dev lo') ]]; then
	echo Routing default target address via loopback device
	sudo ip r add $t dev lo
else
	echo Looks like this is already routed via loopback
fi
echo Adding packet loss to loopback device
sudo tc qdisc add dev lo root netem loss 2%

echo Check everything worked
ip r get $t
tc qdisc show dev lo
echo 2 second ping check to assert packet loss is working
ping -I lo 127.0.0.1 -i 0.002 -w 2 -q
