name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        build-type: [Release]
        raptor: [ON, OFF]
        os: [ubuntu-latest, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: install dependencies
        run: sudo apt install -y gcc ninja-build cmake libssl-dev libboost-all-dev libspdlog-dev libtinyxml2-dev libnl-3-dev pkg-config libconfig++-dev
      - name: pre-cmake
        run: cmake --version && mkdir ${{ github.workspace }}/build && echo `nproc` processing units available
      - name: cmake
        run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DENABLE_RAPTOR=${{ matrix.raptor }}
      - name: build
        run: cd ${{ github.workspace }}/build && ninja -j`nproc`
      - name: check for runtime linking errors in transmitter
        run: ${{ github.workspace }}/build/examples/flute-transmitter --help
      - name: check for runtime linking errors in receiver
        run: ${{ github.workspace }}/build/examples/flute-receiver --help
